export const btnStyle = {
    display: 'inline-block',
    marginBottom: 0,
    fontWeight: 500,
    textAlign: 'center',
    msTouchAction: 'manipulation',
    touchAction: 'manipulation',
    cursor: 'pointer',
    backgroundImage: 'none',
    border: '1px solid transparent',
    whiteSpace: 'nowrap',
    lineHeight: 1.5,
    padding: '4px 15px',
    fontSize: '12px',
    borderRadius: '4px',
    // webkitUserSelect: 'none',
    // mozUserSelect: 'none',
    // msUserSelect: 'none',
    userSelect: 'none',
    // webkitTransition: 'all .3s cubic-bezier(.645,.045,.355,1)',
    transition: 'all .3s cubic-bezier(.645,.045,.355,1)',
    position: 'relative',
    color: 'rgba(0,0,0,.65)',
    backgroundColor: '#fff',
    borderColor: '#d9d9d9'
}
